### ISSUE TITLE
Convert to html:  change output file name

### ISSUE THREAD

**Issue by schmucr1** [bedapub/besca#106]
Hi

In the current workbook the  ipynb to html conversion the output html file is hardcoded which is probably fine in most cases.
but if one uses the same notebook for multiple analysis (copy / paste) it would be convenient if the html output file will automatically have the same name as the jupyter workbook. We could introduce the following code for that (it requires import os)

1st cell:
%%javascript
IPython.notebook.kernel.execute('nb_name = "' + IPython.notebook.notebook_name + '"')

2nd cell:
nb_name = os.path.join(os.getcwd(), nb_name)

3rd cell:
! jupyter nbconvert --to html {nb_name}

**Comment by schmucr1** [comment]
or just include the "analysis_name" variable:

`! jupyter nbconvert --to html {analysis_name}.ipynb `

**Comment by swalpe** [comment]
Thanks for the great suggestion, I've now implemented that in the standard workflow & the cell annotation workflow, it's part of my most recent pull request #107
