### ISSUE TITLE
Change batch correction method for standard workflow

### ISSUE THREAD

**Issue by ajulienla** [bedapub/besca#11]
Current standard workflow is using mnpy as a batch correction method.

Should be changed with bbknn and allow eventually mnpy using a method argument.

Batch correction methods work differently and should be well clarified in the standard worklflow.

MNNPY correction is done before PCA and then PCA is done with method = 'none' in besca

For BBKNN, no initial correction is applied and then a batch column is added in the obs and the method 'bbknn' is used in the pca function

Add message to inform about the correction applied + warning if batch column is not there

**Comment by hatjek** [comment]
I'm much in favor of this, bbknn should be the default.

**Comment by ajulienla** [comment]
Closed a1d216559772f5c54928eb9616bd74986d3c345a
