### ISSUE TITLE
Additional filter on the gene signature scores for omitting irrelevant expression plots

### ISSUE THREAD

**Issue by schmucr1** [bedapub/besca#114]
Suggestion: Additional filter on the gene signature scores
In order to plot only the expression of the relevant gene signatures

Instead of plotting "all" scores by
scores = [x for x in adata.obs.columns if 'scanpy' in x]
sc.pl.umap(adata, color=scores, color_map='viridis')

insert an additional threshold on the maximal detected score, for example, 
score_thr = 1.

scores0 = [x for x in adata.obs.columns if 'scanpy' in x]
scores = [x for x in scores0 if max(adata.obs[x]) > score_thr]
sc.pl.umap(adata, color=scores, color_map='viridis')

Probably there are better thresholds for scores... to be discussed!

**Comment by ajulienla** [comment]
Hi @schmucr1 , 
i think this is a really good sugestion. I ll have a look !
