### ISSUE TITLE
Kernel crashing for bc.st.additional_labeling

### ISSUE THREAD

**Issue by ansonrel** [bedapub/besca#117]
There seems to be a problem with the `bc.st.additional_labeling` function when applied on the merged adata of the RNA and ADT counts of the Granja dataset. The kernel crashes without returning any error message. Strangely, it only happens with this very specific dataset. 

Reproducible example:

```
import besca as bc
import os
import scanpy as sc
adata_prot = bc.datasets.Granja2019_citeSeq()
adata = bc.datasets.Granja2019_raw()
adata_prot = sc.AnnData(adata_prot)
adata_prot.var['ENSEMBL']=adata_prot.var.index
adata_prot.var['SYMBOL']=adata_prot.var.index
adata_prot.var['feature_type']='Anitbody Capture'
adata_prot.obs.CELL = adata_prot.obs.index
adata.obs.CELL = adata.obs.index
adata_merged = bc.concate_adata(adata, adata_prot)
adata_merged.var_names_unique()
adata_merged.raw = adata_merged
adata_merged = bc.st.additional_labeling(adata_merged, labeling_to_use= 'BioClassification', labeling_name = 'BioClassification',
                                      labeling_description = 'test',
                                      labeling_author = 'test', 
                                      results_folder= os.path.join('.'))
```

Some information that me and ajulienla could gather: 
- It crashes with any label.
- It works well with the RNA adata. The problem seems to be due to the concatenating that is done when working with CITEseq data. 
- Replacing the index doesn't work (e.g. adding a `_prot` suffix to the ADT index)
- The crash happens in this loop: https://github.com/bedapub/besca/blob/master/besca/export/_export.py#L1001
- Doing several of the iterations within this loop doesn't crash the kernel. Somehow it is only when all iterations are done that the kernel crashes. It's likely that it is happening at the `scores.merge` step. 
- A new version of the ADTs  will soon be pushed on zenodo and master and somehow resolves the problem. This means that this crash won't happen with the example dataset. Still, it would be nice to identify the problem and add a warning/ fix as it could happen with other datasets.

Thanks!

**Comment by ajulienla** [comment]
We did not manage to reproduce the issue with @ansonrel
