### ISSUE TITLE
Attribute error cell annotation

### ISSUE THREAD

**Issue by derflkent** [bedapub/besca#124]
Hi I'm trying to perform annotation of cell types using this code from the documentation but I'm getting the error below. I was wondering if you had any suggestions of what I need to change?

Thanks

**Code**
gmt_file_anno = pkg_resources.resource_filename('besca', 'datasets/genesets/CellNames_scseqCMs6_sigs.gmt')
mymarkers = bcs.tl.sig.read_GMT_sign(gmt_file_anno, directed=False)
mymarkers = bcs.tl.sig.filter_siggenes(adata, mymarkers)

bcs.tl.sig.combined_signature_score(adata, gmt_file_anno, verbose=False)

**Error**
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-171-e0cc3bd9eb6e> in <module>
      5 mymarkers = bcs.tl.sig.filter_siggenes(adata, mymarkers)
      6 
----> 7 bcs.tl.sig.combined_signature_score(adata, gmt_file_anno, verbose=False)

~/anaconda3/lib/python3.7/site-packages/besca/tl/sig/_sig.py in combined_signature_score(adata, GMT_file, signature_dict, UP_suffix, DN_suffix, method, overwrite, verbose, use_raw, conversion)
    118     # signature_dict=filter_siggenes(adata, signature_dict)
    119     compute_signed_score(adata=adata, signature_dict=signature_dict,
--> 120                          method=method, overwrite=overwrite, verbose=verbose, use_raw=use_raw)
    121     return None
    122 

~/anaconda3/lib/python3.7/site-packages/besca/tl/sig/_sig.py in compute_signed_score(adata, signature_dict, method, overwrite, verbose, use_raw)
    154 
    155     [_handle_signature(signature_dict, method, adata, signature_name, overwrite,
--> 156                        verbose, use_raw) for signature_name in signature_dict.keys()]
    157     return None

~/anaconda3/lib/python3.7/site-packages/besca/tl/sig/_sig.py in <listcomp>(.0)
    154 
    155     [_handle_signature(signature_dict, method, adata, signature_name, overwrite,
--> 156                        verbose, use_raw) for signature_name in signature_dict.keys()]
    157     return None

~/anaconda3/lib/python3.7/site-packages/besca/tl/sig/_metrics.py in _handle_signature(signature, method, adata, signature_name, overwrite, verbose, use_raw)
     58                 currentName = scoreName + direction
     59                 score_genes(adata, signature[signature_name][direction],
---> 60                             score_name=currentName, use_raw=use_raw, copy=False)
     61                 try:
     62                     scoreTMP = adata.obs[currentName]

~/anaconda3/lib/python3.7/site-packages/scanpy/tools/_score_genes.py in score_genes(adata, gene_list, ctrl_size, gene_pool, n_bins, score_name, random_state, copy, use_raw)
    174     elif len(gene_list) == 1:
    175         if _adata[:, gene_list].X.ndim == 2:
--> 176             vector = _adata[:, gene_list].X.toarray()[:, 0] # new anndata
    177         else:
    178             vector = _adata[:, gene_list].X  # old anndata

AttributeError: 'numpy.ndarray' object has no attribute 'toarray'

**Comment by ajulienla** [comment]
Dear @derflkent ,

Could you please provide us with the package version used in your environment ?

In particular I would be interesting into the scanpy and dependencies 
This would be using sc.logging.print_header() ?




Thank you

**Comment by derflkent** [comment]
Hi, thanks for the reply!

sc.logging.print_header()

returns this
scanpy==1.6.1 anndata==0.7.5 umap==0.4.6 numpy==1.19.2 scipy==1.6.0 pandas==1.2.0 scikit-learn==0.23.2 statsmodels==0.12.1 python-igraph==0.8.3 louvain==0.7.0 leidenalg==0.8.3



type( adata.raw.X)

returns this
numpy.ndarray

**Comment by ajulienla** [comment]
Hi @derflkent ,
Based on what I see, this rose from a scanpy issue.
I guess scanpy expect a sparse matrix in X.

Was the adata processed through Besca Standard workflow, or is it from somewhere else?

Could you try out something like this ? :

```
import scanpy as sc
sc.tl.score_genes( adata, gene_list = [ 'TNFRSF13B', 'AIM2', 'CLECL1'], use_raw = True)
```

and let me know if the error is still happening?
If this is the case, this is a scanpy issue. 

Best
Alice

**Comment by derflkent** [comment]
Hi, I removed toarray() from scanpy score_genes and that fixed the issue.

Thanks!

**Comment by ajulienla** [comment]
Great I ll close this then.
