### ISSUE TITLE
Wrong cluster annotation (updated order "ignored"?) 

### ISSUE THREAD

**Issue by llumdi** [bedapub/besca#131]
Hi, 
I am struggling with one thing of the cell annotation notebook (not sure if a bug or I am doing something wrong).
So, after cluster atribution and modifying some cutoffs, I have 2 clusters associated to CD4Tcells:

```
#Cluster attribution based on cutoff
sigscores={}
for mysig in list(df.index):
    sigscores[mysig]=bc.tl.sig.getset(df,mysig,sigconfig.loc[mysig,'Cutoff']*myc)
    #sigscores[mysig]=bc.tl.sig.getset(df,mysig,10)
sigscores

**'CD4Tcell': {'31', '32'},**
```

I changed the order so that CD4 comes first in level 2
```
levsk
['Bcell',
  'ProBcell',
  'CD4Tcell',
  'CD8Tcell',
  'Granulocyte',
  'cDC',
  'pDC',
  'Plasma',
  'CD56dimNK'
  ```
However, I still get cluster 31 annotated as CD8:

```
cnames

celltype0 | celltype1 | celltype2 | celltype3
31 | Hematopoietic | Tcell | CD8Tcell | EMCD8Tcell
```

Thanks for any help,
Llucia

**Comment by ajulienla** [comment]
I have a similar issue; not changing levels but change threshold and not getting the first celltype .
(Example on a public datasets:

 
![Re-annotating ref  Data without dblabel](https://user-images.githubusercontent.com/39824913/142447508-ae65b598-b597-44cf-ba8d-5edd7c7458c7.png)

**Comment by llumdi** [comment]
Hi Alice, 
Thanks for checking this :). 
I just tested it, and I have the same issue when changing the levels as indicated in `celltype_annotation_besca.ipynb`

```
# Optional configuatation: The order of cells at different levels can be manually changed if needed
#levsk[0]=['ColorectalCancer', 'Epithelial','Fibroblast','Endothelial','Erythrocyte','HematoStem',
#          'Hepatocyte','MelMelanoma','Neural','Adipocyte','Hematopoietic','Schwann','Chondrocyte','Glial']
```

Is this also the case for you?
Thanks,
Ll

**Comment by ajulienla** [comment]
Hi Llucia, did you try in the signature_revision  branch?

**Comment by llumdi** [comment]
I have also tested it now with the signature_revision branch and it is indeed fixed :)
