### ISSUE TITLE
AttributeError in labeling() and count_occurrence_subset()

### ISSUE THREAD

**Issue by mariiabilous** [bedapub/besca#150]
I think, `to_frame(name=label)` has to be called after checking if `column` is in `adata.obs.columns`. If `column` in not in `adata.obs.columns`, `.to_frame()` rises error:

>  AttributeError: 'NoneType' object has no attribute 'to_frame'

https://github.com/bedapub/besca/blob/094515e2218c8d9b8952b18ab62f2a3362985936/besca/export/_export.py#L392

Similar problem here: 
https://github.com/bedapub/besca/blob/094515e2218c8d9b8952b18ab62f2a3362985936/besca/tl/_count_occurrences.py#L82

there is no check if `subset_variable` is present, so when it is not present, the error is: 

> AttributeError: 'NoneType' object has no attribute 'value_counts'

**Comment by mariiabilous** [comment]
to be consistent with the package, use:
`try:
    data = adata.obs.get(column).to_frame(name=label)
except KeyError:
    print("Oops!  The adata object does not have the specified column. Options are: ")
    print (list(adata.obs.columns))`

**Comment by swalpe** [comment]
Should now be fixed
