### ISSUE TITLE
Suggestion to also keep signatures with 1 gene

### ISSUE THREAD

**Issue by llumdi** [bedapub/besca#155]
Why bc.tl.sig.filter_siggenes( ) requires minimum 2 genes to keep a signature? `len(mym) > 1`
It is still informative to plot the umap of signatures with only 1 gene expressed in this section of the notebook:

![Snag_14f0fc2b](https://user-images.githubusercontent.com/26581059/115599737-39228300-a2dc-11eb-9328-70dc714df475.png)
(e.g: when inspecting the neutrophil signature in mouse, I receive error in some datasets because the signature was filtered out, despite being one gene expressed)

Is it a requirement to have at least 2 genes for bc.tl.sig.score_mw()?
If so I would suggest to have a parameter for min_genes per signature. So that for inspection is kept to 1 gene and before computing the scores is increased to 2. Just one idea...

Thanks,
Llucia

**Comment by hatjek** [comment]
This was fixed by commit 56c6e17.
