### ISSUE TITLE
Error when using function "combined_signature_score"

### ISSUE THREAD

**Issue by schmucr1** [bedapub/besca#158]
One gets an error "ValueError: No valid genes were passed for scoring.", when none of the genes in a signatures are present in the data set.

**Comment by schmucr1** [comment]
closed as I cannot remember where/how this occurs

**Comment by Accio** [comment]
Hi @schmucr1, the old behaviour happens when no genes are left in a gene-set after filtering or converting to human orthologs. This is now fixed in the issue fix #186.
