### ISSUE TITLE
When citeseq = False, reading matrix should load 'gex_only'

### ISSUE THREAD

**Issue by llumdi** [bedapub/besca#159]
If a dataset contains citeseq data but only the gene data wants to be analyzed, the parameter `citeseq=False` loads both gene and protein counts into the same adata object without warning/error (very dangerous!).

Citeseq parameter only determines if running the citeseq workflow, not if the samples contain citeseq data,
bc.st.read_matrix() function should check if the loaded data contains protein and, if so, do `adata = bc.st.read_matrix(root_path, citeseq = 'gex_only')` even when citeseq false

**Comment by llumdi** [comment]
Here my lightweight solution (change sw notebook):

In chunck 4:
`citeseq = False #specify if run citeseq (protein) analysis 
protein = True # set to true if 1 or more samples have protein data`

Las part of chunk 7:
`else:
    if protein:
        # read only gene data from citeseq
        logging.info('Reading Gene Expression Data...')
        adata = bc.st.read_matrix(root_path, citeseq = 'gex_only') # Samples with protein counts but run analysis on genes only (citeseq=False)
    else:
        #read data
        adata = bc.st.read_matrix(root_path, citeseq = None)`

This is just a suggestion, but I believe a better solution could be implemented.

**Comment by Accio** [comment]
@hatjek: Paul and I disucssed this issue. We think it may make most sense to remove CITE-seq parts from the Standard Workflow, which will render this issue obsolete anyway.

The root cause of this issue is that in the standard workflow, citeseq is a boolean value (True of False). However, for read_mtx, citeseq can take one of three values: `gex_only`, `protein_only`, and `None` which (misleadingly) means gex and protein. 

If we want to keep the CITEseq part in the standard workflow, ideally we change the citeseq variable from a boolean value to string/None to match the signature of `read_matrix`.

**Comment by swalpe** [comment]
hi both thanks a lot for looking into this; i'd be against removing the CITEseq part of the st workflow, it is very useful to have it there. I think even if we change the var to string/None as u suggest, we need to ensure that in case the users suggest the "wrong" value - aka the option for no citeseq, in case they do actually have it, by default the cite-seq part is not read

**Comment by Accio** [comment]
hi @swalpe, thanks for the clarification.

@paulgeser we can discuss this again if you wish.

**Comment by Accio** [comment]
hi @swalpe, I discussed the issue with @paulgeser. We think it may make sense if we allow the `citeseq` variable in the standard workflow take *one of the three values* listed below

* `None`: there is no CITEseq data. If CITEseq data is detected, a warning is emitted that the CITEseq data is ignored.
* `True`: there is CITEseq data and use it. If no CITEseq data is detected, an error/Exception is raised.
* `False`: there is CITEseq data, but DO NOT use it. If no CITEseq data is detected, an error/Exception is raised.

What do you think of this solution?

**Comment by hatjek** [comment]
Hi @Accio and @paulgeser ! I like the solution and would also recommend to keep the CITE-seq analysis in the std workflow.
