### ISSUE TITLE
Inconsistent subsetting function in Besca

### ISSUE THREAD

**Issue by ajulienla** [bedapub/besca#166]
subset_adata helper function is inconsistent. 
If raw = False
returns an object with obs, var, uns, obsm ,varm and obsp.

If raw = True
returned object is only with obs and var.

**Comment by ajulienla** [comment]
In addition,
we should check whether raw is set up initially as default is raw=True.
Otherwise the function fails while trying to copy the raw data.

**Comment by hatjek** [comment]
It's fixed, thanks!
