### ISSUE TITLE
The R code in function `valOutlier` needs modification

### ISSUE THREAD

**Issue by ToryDeng** [bedapub/besca#197]
I'm using Seurat v4.0.5 and it seems that the function `valOutlier` doesn't work with this version of Seurat:
```
rpy2.rinterface_lib.embedded.RRuntimeError: Error in normarg_assays(assays, as.null.if.no.assay = TRUE) : 
  trying to get slot "counts" from an object of a basic class ("NULL") with no slots
```
According to the bug report, I checked the `seurat_obj` in RStudio and found that the data was saved in `originalexp` assay, not `RNA` (in Seurat 3.0). And after I replaced the `RNA` with `originalexp` in `valOutlier`:
```
ro.r(
        "dat =  SingleCellExperiment(assays = list(counts=seurat_obj@assays$originalexp@counts) )"
    )
```
 everything was alright. So maybe you can add `if` and `else` statements to judge the version of Seurat and determine which name of the assay you should use.

**Comment by ToryDeng** [comment]
Dear @kohleman,

I have tested your code. Yes, if you directly import data using R and convert it to the ``Seurat object``, the count matrix is in the ``RNA`` assay. However, in Besaca you actually convert the ``AnnData`` to `SingleCellExperiment` by the Python package ``anndata2ri`` at first, and then you convert the `SingleCellExperiment` to ``Seurat object`` in R:
```python
ro.globalenv["dat"] = adata
ro.globalenv["sym"] = adata.var["SYMBOL"]
ro.r('seurat_obj = as.Seurat(dat, counts="X", data = NULL)')
ro.r(
       "dat =  SingleCellExperiment(assays = list(counts=seurat_obj@assays$RNA@counts) )"
   )
```
So if you want to reproduce the error, you can try the following code:
```python
# in Python
import anndata2ri
from rpy2.robjects import r, globalenv

anndata2ri.activate()
globalenv['dat'] = adata
r("save(dat, file = '/path/to/Rdata')")
anndata2ri.deactivate()
```

```R
# in R
require(Seurat)

load("/path/to/Rdata")
seurat_obj = as.Seurat(dat, counts="X", data = NULL)
dat =  SingleCellExperiment(assays = list(counts=seurat_obj@assays$RNA@counts))
```
and you should see an error report:
```
Error in normarg_assays(assays, as.null.if.no.assay = TRUE) : 
  trying to get slot "counts" from an object of a basic class ("NULL") with no slots
```
and if you check the assay in ``seurat_obj``, you should see similar output like this:
```
> seurat_obj@assays
$originalexp
Assay data with 772 features for 3331 cells
First 10 features:
 ISG15, AURKAIP1, SSU72, RPL22, PARK7, ENO1, CAPZB, MINOS1, DDOST,
CDC42
```
I guess the conversion between ``SingleCellExperiment`` and ``Seurat object`` using the function ``as.Seurat`` makes the error happen. Actually, I checked the source code of ``as.Seurat.SingleCellExperiment`` in Seurat v4.1.1 and found the following code:
```R
if (packageVersion(pkg = "SingleCellExperiment") >= "1.14.0") {
    orig.exp <- SingleCellExperiment::mainExpName(x = x) %||% "originalexp"
  } else {
    orig.exp <- "originalexp"
  }
  if (!is.null(SingleCellExperiment::altExpNames(x = x))) {
    assayn <- assay %||% SingleCellExperiment::altExpNames(x = x)
    if (!all(assay %in% SingleCellExperiment::altExpNames(x = x))) {
      stop("One or more of the assays you are trying to convert is not in the SingleCellExperiment object")
    }
    assayn <- c(orig.exp, assayn)
  } else {
    assayn <- orig.exp
  }
```
I hope this will help you.

**Comment by kohleman** [comment]
Thanks for your explanations and code samples. I will try it out.

**Comment by kohleman** [comment]
Dear @ToryDeng,
I will change the code to this:
```
if (packageVersion("Seurat") >= "4.0" ) {
  print("Detected Seurat Version >= 4")
  dat =  SingleCellExperiment(assays = list(counts=seurat_obj@assays$originalexp@counts))
  
} else {
  print("Detected Seurat Version < 4")
  dat =  SingleCellExperiment(assays = list(counts=seurat_obj@assays$RNA@counts))
}
```

**Comment by kohleman** [comment]
fixed in https://github.com/bedapub/besca/commit/9945d73fe8ccfc8124b092222d04b08246e1f00b
