### ISSUE TITLE
README update: python version

### ISSUE THREAD

**Issue by xanubsl** [bedapub/besca#204]
Within the README, conda instructions still call for python=3.7.1 while newest besca requires python 3.8.

**Comment by paulgeser** [comment]
Will take a look at the issue

**Comment by paulgeser** [comment]
After checking I saw that the version was already upgraded to 3.9

**Comment by paulgeser** [comment]
Please tell me, if the issue is with that resolved, then I can close the issue

**Comment by hatjek** [comment]
Can we close this issue @paulgeser or @yannik-benndorf ?

**Comment by paulgeser** [comment]
Implementation has been merged(#235) into master, therefore this issue will be closed.
