### ISSUE TITLE
Rasterize Scatter Plots

### ISSUE THREAD

**Issue by Artemis-R** [bedapub/besca#21]
Currently our self-made scatter plots (e.g. the filtering plots) are not rasterized. Since we have the same number of dots as cells this leads to issues when trying to work with exported pdf images of these plots since depending on your number of cells you have 100,000+ objects in your vector graphic (very slow in all vector graphic editing software).

This can be fixed by calling the parameter rasterized = true when using the matplotlib scatter function (see [here](https://stackoverflow.com/questions/44251973/vector-axes-but-raster-points-for-matplotlib-scatter-plots) and [here](https://matplotlib.org/api/_as_gen/matplotlib.artist.Artist.set_rasterized.html#matplotlib.artist.Artist.set_rasterized)). This makes the figures much easier to work with and is also what the scanpy people use to plot e.g. UMAPS (the axis and labels are still vector graphics but the dots from the UMAP have been converted to a rasterized image). 

I think it makes sense to implement this. I see no reason why we would want the plots with the individual points as vector graphic images. It makes all downstream work with the figures difficult.

I have implemented this fix in a branch (see  https://github.com/bedapub/besca/tree/rasterize_scatter_plots). Does anyone see any issues with changing the plots in this way?

**Comment by hatjek** [comment]
Makes sense and looks good to me!

**Comment by Artemis-R** [comment]
closed in bf2efe5
