### ISSUE TITLE
Omit or replace R functions

### ISSUE THREAD

**Issue by hatjek** [bedapub/besca#217]
We have multiple R functions used in the standard workflow. They can all be found in this file:
https://github.com/bedapub/besca/blob/master/besca/st/_wrapper_Rfuncs.py
The R code makes the installation and maintenance difficult. We should either remove them or replace them by Python code. See also: #144 #197

**Comment by kohleman** [comment]
As already discussed internally, not that simple to rewrite the R code in python as several R packages are involved which also employ some C++ code

**Comment by hatjek** [comment]
Hi @kohleman ! I would suggest that we remove the R methods from the std workflow for v2.5 and mark them as deprecated. Than people don't feel obliged to install all the R dependencies. In the future, we can look for better alternatives if still needed. OK?

**Comment by kohleman** [comment]
Fine for me 👍
