### ISSUE TITLE
pip install error

### ISSUE THREAD

**Issue by luiswyss** [bedapub/besca#22]
When installing besca in an empty conda environment containing only pip, the installation fails due to errors with the dependency "annoy" (ERROR: Failed building wheel for annoy).
Manually installing annoy (for example with:  conda install -c conda-forge python-annoy) before running the pip installation of besca circumvents the issue. Nevertheless, it would be ideal if it weren't necessary. I don't really have any experience with managing pip installations but maybe someone else is more knowledgeable.

**Comment by ajulienla** [comment]
Hi Luis, 
unfortunately we never managed to reproduce this kind of issue. We already had this during the BESCA PUB sprint. You and I have problem that Eric and others do not encounter. If someone has more knowledge of it I am happy to hear more thoughts.

**Comment by Artemis-R** [comment]
I just did a complete clean install (i.e. new MacOS, new python distribution, etc.) and had no issues with the installation. Pip install worked perfectly fine. If you have more information for me @luiswyss on how I could recreate this issue I would look into.

**Comment by luiswyss** [comment]
Sure, I work with the linux subsystem for windows and I used the most recent python and conda installations and create a new empty environment. There I install only pip ( conda install -c anaconda pip ) and then run the pip installation command for besca. Pip starts downloading all necessary dependencies until it gets to annoy where it reports:
` Building wheel for annoy (setup.py) ... error                                                            ERROR: Command errored out with exit status 1:                                                            command: /home/luis/anaconda3/envs/besca-test06/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-0gnlc4e5/annoy/setup.py'"'"'; __file__='"'"'/tmp/pip-install-0gnlc4e5/annoy/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-obp_45h1                                                                                                        cwd: /tmp/pip-install-0gnlc4e5/annoy/                                                               Complete output (14 lines):                                                                              running bdist_wheel                                                                                      running build                                                                                            running build_py                                                                                         creating build                                                                                           creating build/lib.linux-x86_64-3.8                                                                      creating build/lib.linux-x86_64-3.8/annoy                                                                copying annoy/__init__.py -> build/lib.linux-x86_64-3.8/annoy                                            running build_ext                                                                                        building 'annoy.annoylib' extension                                                                      creating build/temp.linux-x86_64-3.8                                                                     creating build/temp.linux-x86_64-3.8/src                                                                 gcc -pthread -B /home/luis/anaconda3/envs/besca-test06/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/luis/anaconda3/envs/besca-test06/include/python3.8 -c src/annoymodule.cc -o build/temp.linux-x86_64-3.8/src/annoymodule.o -D_CRT_SECURE_NO_WARNINGS -march=native -O3 -ffast-math -fno-associative-math                                                       unable to execute 'gcc': No such file or directory                                                       error: command 'gcc' failed with exit status 1                                                           ----------------------------------------                                                                 ERROR: Failed building wheel for annoy     `

Installing annoy separately with  conda install -c conda-forge python-annoy  works, and after having executed above command, the pip installation of besca works without any issues. 
I hope I could clarify the situation a little, I don't really have an idea what could be the cause...
