### ISSUE TITLE
Cell annotation notebook related

### ISSUE THREAD

**Issue by swalpe** [bedapub/besca#25]
Shall we add an automatic annotation example in the cell annotation notebook? I think it would make sense, ppl would have it on one place then

**Comment by hatjek** [comment]
Yes, let's add some examples once we have them in good shape. So far, we have this tutorial in the documentation, but would need to update the train dataset:
https://bedapub.github.io/besca/tutorials/auto_annot_tutorial.html
https://github.com/bedapub/besca/blob/master/docs/source/tutorials/auto_annot_tutorial.ipynb

**Comment by ajulienla** [comment]
@swalpe this is done by your last improvment right ? Should we close this ?
