### ISSUE TITLE
Some chunks get lost byopening notebooks in JupyterLab (instead of classical Jupyter notebook)

### ISSUE THREAD

**Issue by hatjek** [bedapub/besca#251]
Especially in the standard workflow, some chunks get lost when opening notebooks in JupyterLab (instead of classical Jupyter notebook), preventing the workflow to finish. We should prepare notebooks that can be opened by both, JupyterLab and classical Jupyter notebook.

**Comment by kohleman** [comment]
Everything runs with jupyter lab as well. 
Tested with:
IPython             8.4.0
jupyter_client      7.3.4
jupyter_core        4.10.0
jupyterlab          3.4.2
notebook            6.4.12
