### ISSUE TITLE
Installation fail: unable to resolve dependencies

### ISSUE THREAD

**Issue by jpiggod** [bedapub/besca#269]
I was following the recommended steps to install `besca` in a new conda environment, i.e. basically copy-and-pasting the codes under the Section "Python beginner guide".

However, it paused for a long time (10+ hours; so it's more like getting stuck at this step while it used more than 100GB of my memory as I finally realized...) while I was trying to install R and the related packages:
```
conda install -y -c conda-forge r=4.0 rpy2 r-essentials r-base r-devtools r-withr r-vctrs r-tidyverse r-magrittr r-data.table r-Matrix r-ggplot2 r-readr r-seurat r-intrinsicdimension r-mclust r-sitmo r-patchwork --force-reinstall
```

Metadata collection for the packages was successfully done after a short while, but it seems it failed at the "solving environment" step?
```
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Collecting package metadata (repodata.json): done
Solving environment: / 
```

I also updated my conda by `conda update conda` after the initial fail, but I was still stuck at the same step. 
May I know if you have any idea to solve this issue?

**Comment by hatjek** [comment]
Dear @jpiggod ,

Thank you very much for your interest in Besca. The R wrapper functions are deprecated since Besca release 2.5, therefore we don't support those anymore. 

Is there a specific function you would need from the R wrappers? Otherwise I would suggest to stay with the Python-only version, basically `pip install besca` should do the magic.

Best wishes
Klas

**Comment by jpiggod** [comment]
Hi @hatjek 

Thanks so much for your explanation! I thought it's still required to install the R dependencies separately in order to make full use of the `besca`/`bescape` utilities. Sorry for not having read the manual in detail.
