### ISSUE TITLE
Error in neutrophil signature

### ISSUE THREAD

**Issue by llumdi** [bedapub/besca#289]
There is a typo in the .gmt file for the neutrophils signature.

`mymarkers = bc.tl.sig.read_GMT_sign(gmt_file_anno, directed=False)`
`mymarkers['Neutrophil']`

Output: ['ELANE', 'MPO', 'PRTN3', 'CTSG', 'AZU1', 'FCGR3B CXCR2  ']

@kohleman can you fix the gmt file (`besca/datasets/genesets/CellNames_scseqCMs6_sigs.gmt`) so that FCGR3B and CXCR2 genes are read correctly? I though I fixed it in my last commit, but apparently not...
Thanks a lot

**Comment by swalpe** [comment]
Fixed both human and mouse
