### ISSUE TITLE
`IndexError: list index out of range` while running the cell annotation workbook

### ISSUE THREAD

**Issue by matchy233** [bedapub/besca#299]
I was trying to run [the latest cell annotation workbook](https://github.com/bedapub/besca/tree/master/workbooks) on Roche's sHPC platform using jupyter lab with the besca2.5.3 kernel provided. The notebook was expected to run without errors, but I encountered `IndexError` in cell 46 (the cell number if you click "run all").

The error screenshot was attached below.

![image](https://github.com/bedapub/besca/assets/32197833/e21a1168-2284-48cb-8cf3-b52015a070c9)

**Comment by matchy233** [comment]
I've already identified the root cause of this error: it's related to [the `read_annotconfig` function in besca/besca/tl/sig/_annot.py](https://github.com/bedapub/besca/blob/master/besca/tl/sig/_annot.py#L124-L167).

I'm not sure since when but at least for `pandas v2.0.2`, `pd.read_csv` will replace all `NaN`-like values (including `"None"`) with `NaN` when you read a csv/tsv file.

So the "None"s in `sigconfig` will be replaced by `NaN` in the current implementation and thus will affect the building of `levs`, resulting the function returning an empty `levsk` list. This consequently cause the index out of range error.

We could fix this by:

1. Add `keep_default_na=False` to `read_csv`
2. Add `na_filter=False` to `read_csv`
3. Do not use `sigconfig["Parent"] == "None"` as the filtering criterion

Any of the fix is pretty easy so I can raise a PR for it after a dev review this issue.

**Comment by kohleman** [comment]
Hi @matchy233, this sounds good to me. You can go ahead with your PR
