### ISSUE TITLE
Bug bc.tl.sig.combined_signature_score(adata=adata, GMT_file= '../besca/datasets/genesets/Immune.gmt', use_raw=True, verbose = False)

### ISSUE THREAD

**Issue by ajulienla** [bedapub/besca#4]
DImension error.
See testing notebook (commented for now).

**Comment by ajulienla** [comment]
Pinpoint by swalpe: 

> 
> bc.tl.sig.combined_signature_score(tmp, gmt_file,
>                              UP_suffix='_UP', DN_suffix='_DN', method='scanpy',
>                              overwrite=False, verbose=False,
>                              use_raw=True, conversion=None)
> 
> and 
> bc.tl.sig.combined_signature_score(adata, gmt_file_IMM)
> 
> But both give errors. I think it's an error because of the scanpy sig scoring function and it happens when only 1 gene is present from the signature set. Perhaps we can add some filter to eliminate such cases? E.g. I typically run a check 
> 
> mymarkers={}
> for key, value in annotSigns.items():
>     mym=[]
>     for item in value:
>         if (sum(adata.raw.var.index.isin([item])*1)>0):
>             mym.append(item)
>     if (len(mym)>1): mymarkers[key]=mym
> 
> Cheers,

**Comment by swalpe** [comment]
I now have a function bc.tl.sig.filter_siggenes(adata, sigdict) that can remove missing genes and signatures < 2 genes; does it make sense to use such filtering in the signature functions?

**Comment by ajulienla** [comment]
CLosed by swalpe fix
