### ISSUE TITLE
Continuous integration workflows

### ISSUE THREAD

**Issue by nahanoo** [bedapub/besca#47]
Hi I remember that we planned to implement some CI tests which I think would be really helpful considering that more and more pull requests are submitted. 

So what's the current state on that?

I can take over implementing a CI which tests package building and importing.

**Comment by Accio** [comment]
Hi @nahanoo, please go ahead. I plan to add testing, too.

Which test software do you prefer? I plan to use py.test (or unittest) and hypothesis.

Let me know how you would like to see it done. I am glad to help.

**Comment by nahanoo** [comment]
I'm open to whatever testing library you want to use, I'm easy.

I think this will be pretty time consuming to implement.
Maybe more as a temporary solution I was thinking to just automatically run through the standard workflow. Obviously a lot less fancy but for now it would maybe do the job.

What do you think?

Best,
Eric

**Comment by ajulienla** [comment]
Closed for now; please re-open when someone has time to work on it.
