### ISSUE TITLE
UMAP in standard workflow may fail 

### ISSUE THREAD

**Issue by Accio** [bedapub/besca#53]
Due to this line: sc.pl.umap( adata, color=['PTPRC', 'CD14'], color_map = 'viridis')

If the genes are filtered out, this line will fail.

Suggestions: maybe we can set these genes in a data-driven manner, or put them in the settings session at the beginning.

**Comment by swalpe** [comment]
Yes good point, we had introduced that just as examples but indeed they are dataset-specific. I think replacing with a parameter as u suggest would be a good solution.

**Comment by ajulienla** [comment]
Fix in commit dd85122e25a77600a193906c2821f7d7870405b8
