### ISSUE TITLE
Standardization of the annotation function

### ISSUE THREAD

**Issue by ajulienla** [bedapub/besca#7]
Standardization of the annotation function to have more user-defined:

thresholds
annotation
@schwalip will have a look at thresholding and more signatures/specifications
@julienla will have a look at structuring rules for user-defined trees.

**Comment by ajulienla** [comment]
Current proposal is to work on a config file to set up the different threshold. Thus this can be modified by user.

**Comment by ajulienla** [comment]
Additional things to add would be to allow a restriction of the annotation levels as detailled ones might be too specific and need more personalized checks

**Comment by ajulienla** [comment]
TODO:
+ Add hierachy of the immune  (from more speific to less specific signatures) as user-definable
+ Add EFO CL ID

**Comment by ajulienla** [comment]
Add unsigned possibility in signature fucntion to fit the gmt files provided in Besca

**Comment by swalpe** [comment]
Remove legacy annotation functions now called _torem

**Comment by ajulienla** [comment]
@swalpe  what do you think of providing a parameter for the config reading file to focus on specifc cell type (eg. pmbc does not need endo signature). 
Could be just to skip some lines of the confi files.

**Comment by swalpe** [comment]
Actually I added an option to exclude individual terms - toexclude=[], takes a list. This keeps things relatively flexible and you can just ignore what you don't need/is troublesome. We should include this as an example in the cell annot notebook & also it's currently not documented as a parameter, i'll fix that. Does it make sense @ajulienla ?

**Comment by ajulienla** [comment]
@swalpe  yes I saw this, this is in the computation thanks.

I was thinking also at the level of computing the signatures to avoid having non related signatures in the processed file but I do not see easy solution right now as this is from a gmt that the user should probably clean up itself.

**Comment by swalpe** [comment]
The pDC signature doesn't seem to translate well mouse-human one either needs two or additional better markers should be chosen

**Comment by ajulienla** [comment]
This is done in besca24
