### ISSUE TITLE
Add riverplot: 1 X 1  comparison; for example for annootation

### ISSUE THREAD

**Issue by ajulienla** [bedapub/besca#73]
Prepare some plotting function to compare bettwen annotation something like:

bc.pl.compare_river( adata, col1 = 'dblabel', col2 = 'auto_annot_dblabel')

Would give example taken for LIGER publication (https://www.cell.com/cell/pdf/S0092-8674(19)30504-5.pdf)
(here they have 3 sets to compare. We could focus inirtially on 2....)
![image](https://user-images.githubusercontent.com/39824913/89024058-cf64e200-d324-11ea-9a88-b70f33b370c1.png)

**Comment by Artemis-R** [comment]
I really like the idea. It's a nice way to compare the annotation types. It should hopefully not be too complicated too implement.

**Comment by ajulienla** [comment]
Done for 2 categories in  ccb8b29da3f4c2821d0a90e89df737fb830dceb8
