### ISSUE TITLE
Bug in celltype_annotation_besca.ipynb - path to besca directory

### ISSUE THREAD

**Issue by andreea1110** [bedapub/besca#79]
There is an issue in the **celltype_annotation_besca.ipynb** (second cell in the current version) where the standardized file paths are defined, namely, ```bescapath=os.path.split(root_path)[0]``` points to the working directory, which is not the directory containing the subdirectories **/besca/datasets/** needed for subsequent steps.

The besca datasets which were downloaded with the besca installation are saved (if besca is installed in a python3.7 conda environment named "besca") for each &lt;user> at the path:
/pstore/home/&lt;user>/.conda/envs/besca/lib/python3.7/site-packages/besca/datasets/

Hence, bescapath should point to **/pstore/home/&lt;user>/.conda/envs/besca/lib/python3.7/site-packages/**, which can be done using the code 

```
bescapath_full = os.path.dirname(bc.__file__)
bescapath = os.path.split(bescapath_full)[0]
```
instead of the current:

```
root_path = os.getcwd()
bescapath=os.path.split(root_path)[0]
```

**Comment by ajulienla** [comment]
@andreea1110  thank you for reporting and providing the solution.

**Comment by andreea1110** [comment]
@Artemis-R Thanks for the quick response :) 
Just another small issue: I've had a look at the commit and noticed you removed 
```
root_path = os.getcwd()
```
completely. However, this variable is still needed later in the code, e.g. when creating the path for the *analyzed* folder
```
results_folder = os.path.join(root_path, 'analyzed', analysis_name)
```

Thus, I think it should be re-included in the second cell, which should finally look like

```
#define standardized filepaths based on above input
root_path = os.getcwd()
bescapath_full = os.path.dirname(bc.__file__)
bescapath = os.path.split(bescapath_full)[0]

### Uncomment this when running after the standard workflow
analysis_name = 'standard_workflow_besca2.0'

clusters='leiden'
```

**Comment by Artemis-R** [comment]
@andreea1110 yes thanks. I just committed a fix. Should hopefully get reviewed soon and then merged.
