### ISSUE TITLE
Documentation Issues

### ISSUE THREAD

**Issue by sophiamaedler** [bedapub/besca#95]
I've noticed a couple of issue with the documentation that need to be addressed:

- on the tutorials page the legend on the sidebar is very messed up and includes things that probably shouldn't be there (e.g. Done!), also the order of the tutorials in the sidebar should be set to something logical

<img width="302" alt="Screen Shot 2020-08-22 at 18 08 30" src="https://user-images.githubusercontent.com/15019107/90960550-a3abc680-e4a2-11ea-9dee-ed766d772eea.png">

- in the automatic annotation tutorial the graphs are strangely sqaushed. Any way of fixing this @mirophan? 

<img width="790" alt="Screen Shot 2020-08-22 at 18 07 42" src="https://user-images.githubusercontent.com/15019107/90960574-cfc74780-e4a2-11ea-99ef-e8f76d26d77f.png">

**Comment by Artemis-R** [comment]
> thanks! the first one was fixed in my tutorial-fix PR, please re-generate the documentation. Best regards, David Am Sa., 22. Aug. 2020 um 18:11 Uhr schrieb Artemis-R < notifications@github.com>:
> […](#)

Perfect I'll recompile today.

**Comment by Artemis-R** [comment]
> Hi,
> 
> thank you for raising the issue. @luiswyss can you check on the automatic annotation tutorial?
> 
> Best,
> Miro

Thanks. Sorry I somehow thought you had done that tutorial.
